baseurl = "https://jiro4989.github.io/"
# languageCode = "en-us"
languageCode = "ja-jp"
hasCJKLanguage = true
title = "次ログ"
# Enable comments by entering your Disqus shortname
disqusShortname = "https-jiro4989-github-io"
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""
# Define the number of posts per page
paginate = 10
footnotereturnlinkcontents = "↩"
theme = "icarus"
#theme = "sam"
# Comment the themesDir option if you use this theme in production
# themesDir = "../.."

[permalinks]
    post = "/post/content/:year/:month/:day/:slug"

[params]
    # Tell me who you are
    author = "次郎"
    bio = "SIer勤務のWeb系エンジニア"
    location = "日本"
    site_description = "技術、ツールやイラスト配布、RPGツクールの話など"
    copyright  = "Jiro. Powered by [Hugo](//gohugo.io). Theme by [PPOffice](http://github.com/ppoffice)."
    avatar = "css/images/avatar.png"
    # Enter your email address to display your Gravatar icon in the profile. If not set the theme
    # will fallback to the avatar.
    gravatar = "jiroron666@gmail.com"
    logo = "css/images/logo.png"
    disable_mathjax = false # set to true to disable MathJax

    # define which types of pages should be shown. By default the type with the most regular pages
    mainSections = ["post"]

    # Format dates with Go's time formatting
    date_format = "2006-01-02"

# Create custom menu entries by defining a label and a link for
# them. Since you can also link posts, you've the option the
# place the links before or after them.

# E.g.: "Home" appears before all linked posts in the menu
# and "Tags" / "Categories" after them.
[[params.menu]]
    before = true
    label  = "Home"
    link   = "/"

[[params.menu]]
    before = false
    label  = "Tags"
    link   = "tags/"

[[params.menu]]
    before = false
    label  = "Categories"
    link   = "categories/"

[[params.menu]]
    before = false
    label  = "Repository"
    link   = "https://github.com/jiro4989/jilog-hugo"


[[params.menu]]
    before = false
    label  = "Illust"
    link   = "https://jiro4989.github.io/dist-illust/"

# Enter a link for the follow button on the left
[params.profile]
    follow_button = "https://twitter.com/jiro_saburomaru"


[social]
# Add your social network accounts to the profile section on the left
# by entering your username. The links to your account will be
# created automatically.
    github          = "jiro4989"
    gitlab          = ""
    bitbucket       = ""
    jsfiddle        = ""
    codepen         = ""
    foursquare      = ""
    dribbble        = ""
    deviantart      = ""
    behance         = ""
    flickr          = ""
    instagram       = ""
    youtube         = ""
    vimeo           = ""
    vine            = ""
    medium          = ""
    wordpress       = ""
    tumblr          = ""
    xing            = ""
    linkedin        = ""
    slideshare      = ""
    stackoverflow   = ""
    reddit          = ""
    pinterest       = ""
    googleplus      = ""
    facebook        = ""
    facebook_admin  = ""
    twitter_domain  = ""
    twitter         = "jiro_saburomaru"

# Enable and disable widgets for the right sidebar
[params.widgets]
    recent_articles = true
    categories = true
    tags = true
    tag_cloud = true
